// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5hGcd0OhJW0AwRiHC4Hk39fNebddK88',
    appId: '1:361347761242:web:c709e909ba676dfeb44463',
    messagingSenderId: '361347761242',
    projectId: 'mynotes-flutter-project11',
    authDomain: 'mynotes-flutter-project11.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVK4c5KyhAMezkUYj2mop9fbAH1-JNBGM',
    appId: '1:361347761242:android:85c9c61b1419ff24b44463',
    messagingSenderId: '361347761242',
    projectId: 'mynotes-flutter-project11',
    storageBucket: 'mynotes-flutter-project11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVt7DoYRICvhG8F_ErqXZ3jjUUqJ3D4Kk',
    appId: '1:361347761242:ios:fc6eef16c554ca71b44463',
    messagingSenderId: '361347761242',
    projectId: 'mynotes-flutter-project11',
    storageBucket: 'mynotes-flutter-project11.appspot.com',
    iosClientId:
        '361347761242-r1ur7h059hoq8igshj7pi6r28sdt7r64.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVt7DoYRICvhG8F_ErqXZ3jjUUqJ3D4Kk',
    appId: '1:361347761242:ios:fc6eef16c554ca71b44463',
    messagingSenderId: '361347761242',
    projectId: 'mynotes-flutter-project11',
    storageBucket: 'mynotes-flutter-project11.appspot.com',
    iosClientId:
        '361347761242-r1ur7h059hoq8igshj7pi6r28sdt7r64.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
